micronaut-projects/micronaut-test-resources

- test-resources-hivemq/build.gradle
- test-resources-hivemq/src/test/groovy/io/micronaut/testresources/hivemq/AbstractHiveMQSpec.groovy
- test-resources-hivemq/src/test/groovy/io/micronaut/testresources/hivemq/HiveMQNotStartedTest.groovy
- test-resources-hivemq/src/test/groovy/io/micronaut/testresources/hivemq/HiveMQStartedTest.groovy
- test-resources-jdbc/test-resources-jdbc-core/build.gradle
- test-resources-jdbc/test-resources-jdbc-core/src/testFixtures/groovy/io/micronaut/testresources/jdbc/AbstractJDBCSpec.groovy
- test-resources-kafka/build.gradle
- test-resources-kafka/src/test/groovy/io/micronaut/testresources/kafka/AbstractKafkaSpec.groovy
- test-resources-kafka/src/test/groovy/io/micronaut/testresources/kafka/CustomKafkaImageTest.groovy
- test-resources-kafka/src/test/groovy/io/micronaut/testresources/kafka/KafkaNotStartedTest.groovy
- test-resources-kafka/src/test/groovy/io/micronaut/testresources/kafka/KafkaStartedTest.groovy
- test-resources-mongodb/build.gradle
- test-resources-mongodb/src/test/groovy/io/micronaut/testresources/mongodb/AbstractMongoDBSpec.groovy
- test-resources-neo4j/build.gradle
- test-resources-neo4j/src/test/groovy/io/micronaut/testresources/neo4j/AbstractNeo4jDBSpec.groovy
- test-resources-testcontainers/build.gradle
- test-resources-testcontainers/src/testFixtures/groovy/io/micronaut/testresources/testcontainers/AbstractTestContainersSpec.groovy
So that all projects using Testcontainers use the same base test
class.
> Refactor test fixtures

- src/main/docs/guide/modules-testcontainers.adoc
- test-resources-kafka/src/test/groovy/io/micronaut/testresources/kafka/CustomKafkaImageTest.groovy
- test-resources-testcontainers/build.gradle
- test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/AbstractTestContainersProvider.java
- test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/GenericTestContainerProvider.java
- test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java
- test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java
- test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy
This commit adds more configuration options to both generic
test containers and supported containers.
> Add more options to test containers

- buildSrc/src/main/groovy/io.micronaut.build.internal.server-module.gradle
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- test-resources-server/build.gradle
> Optimize server with Micronaut AOT

- test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java
- test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
So that we can share startup optimization params between Maven and Gradle.
> Add JVM startup options to the process parameters

- test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java
- test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/TestResourcesClasspathTest.groovy
> Add more inference for Mongo

- test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java
- test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
> Fix port file contents not always being readable

- src/main/docs/guide/quickStart.adoc
See https://github.com/micronaut-projects/micronaut-maven-plugin/pull/436
[skip ci]
> Update Maven quick start

- src/main/docs/guide/modules-mongodb.adoc
- test-resources-mongodb/src/main/java/io/micronaut/testresources/mongodb/MongoDBTestResourceProvider.java
- test-resources-mongodb/src/test/groovy/io/micronaut/testresources/mongodb/CustomDbNameMongoDBTest.groovy
- test-resources-mongodb/src/test/resources/application-custom-db-name.yml
> Let the user choose a custom db name

- test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java
- test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
> Let the user pick a namespace for the default settings directory

- src/main/docs/guide/modules-testcontainers.adoc
- test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java
- test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java
- test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy
> Add support for wait strategies

- test-resources-client/src/main/java/io/micronaut/testresources/client/DefaultTestResourcesClient.java
Fix test resources failing when only Micronaut Serde is present (not jackson).
> [backport] Correct use of generics

- .github/workflows/graalvm.yml
- settings.gradle
- src/main/docs/guide/modules-databases.adoc
- src/main/docs/guide/modules-hashicorp-vault.adoc
- src/main/docs/guide/modules-mqtt.adoc
- src/main/docs/guide/modules-testcontainers.adoc
> Migrate to new configuration asciidoc macro and build plugin 5.4.5

- buildSrc/build.gradle
- buildSrc/src/main/groovy/io.micronaut.build.internal.server-module.gradle
- test-resources-embedded/src/main/java/io/micronaut/testresources/embedded/TestResourcesResolverLoader.java
- test-resources-server/build.gradle
Until a version of the Gradle plugin compatible with Micronaut 4 is out.
> Use a fat jar for the test resources service

- test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java
- test-resources-jdbc/test-resources-jdbc-oracle-xe/src/main/java/io/micronaut/testresources/oracle/xe/OracleXETestResourceProvider.java
> Avoid trying to get datasource name from non-datasource expressions

- src/main/docs/guide/modules-localstack.adoc
- src/main/docs/guide/toc.yml
> Document localstack support

- config/accepted-api-changes.json
- settings.gradle
- test-resources-bom/build.gradle.kts
- test-resources-hibernate-reactive/test-resources-hibernate-reactive-core/src/testFixtures/groovy/io/micronaut/testresources/hibernate/reactive/core/Book.groovy
- test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/src/test/groovy/io/micronaut/testresources/hibernate/reactive/mariadb/StandaloneStartMariaDBTest.groovy
- test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/src/test/groovy/io/micronaut/testresources/hibernate/reactive/mariadb/WithJdbcStartMariaDBTest.groovy
- test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/src/test/groovy/io/micronaut/testresources/hibernate/reactive/mysql/StandaloneStartMySQLDBTest.groovy
- test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/src/test/groovy/io/micronaut/testresources/hibernate/reactive/mysql/WithJdbcStartMySQLDBTest.groovy
> Re-enable Hibernate reactive support

- buildSrc/src/main/groovy/io.micronaut.build.internal.test-fixtures.gradle
- test-resources-hibernate-reactive/test-resources-hibernate-reactive-core/build.gradle
- test-resources-jdbc/test-resources-jdbc-core/build.gradle
- test-resources-localstack/test-resources-localstack-core/build.gradle
- test-resources-testcontainers/build.gradle
Reverts micronaut-projects/micronaut-test-resources#197
> Revert "Remove publication of test fixtures"

- test-resources-server/src/main/resources/logback.xml
> Prefix Test Resources Service logs

- buildSrc/build.gradle
- test-resources-server/build.gradle
- test-resources-server/src/main/resources/application.properties
- test-resources-server/src/main/resources/application.yml
This slightly reduces the size of the test resources service jar.
> Remove YAML dependency on the server

- src/main/docs/guide/modules-testcontainers.adoc
- test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java
- test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java
- test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainersConfiguration.java
- test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy
Allow configuration of network mode which enables attaching test containers to an existing network.
> Add support for network mode

- README.md
- test-resources-server/src/test/groovy/io/micronaut/testresources/server/TestResourcesControllerTest.groovy
> Gradle Enterprise rename

- test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java
Normally, this is handled by ruyk. But if for some reason Ruyk is not available, we have to close them manually.
> Close containers on shutdown
