micronaut-projects/micronaut-test-resources

settings.gradle, test-resources-build-tools/build.gradle, test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/MavenDependency.java, test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java, test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/TestResourcesClasspathTest.groovy
This will make it simpler if we add more common stuff to this module
later.
=> Rename `classpath` -> `build-tools`

buildSrc/src/main/groovy/io/micronaut/internal/WriteModuleList.java, test-resources-build-tools/build.gradle, test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java
This interface contains the list of known modules from the project,
so that build tools don't have to maintain their own list.
That interface will be extended by the Gradle DSL directly, so that
users can have completion on module names.
=> Introduce `KnownModules`

src/main/docs/guide/modules-testcontainers.adoc, test-resources-kafka/src/test/groovy/io/micronaut/testresources/kafka/KafkaCustomConfigTest.groovy, test-resources-kafka/src/test/resources/application-custom.yml, test-resources-kafka/src/test/resources/example/kafka_server_jaas.conf, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java, test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy, test-resources-testcontainers/src/test/resources/some/file.txt
This commit adds support for copying files to container. As a
proof-of-concept, it adds a test to the Kafka module which uses
both environment variables and a custom SASL configuration,
which requires copying files to the container before it starts.
=> Add support for copying files to containers

buildSrc/src/main/groovy/io.micronaut.build.internal.jdbc-module.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.r2dbc-module.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.testcontainers-module.gradle, test-resources-hivemq/build.gradle, test-resources-jdbc/test-resources-jdbc-core/build.gradle, test-resources-jdbc/test-resources-jdbc-mariadb/build.gradle, test-resources-jdbc/test-resources-jdbc-mssql/build.gradle, test-resources-jdbc/test-resources-jdbc-mysql/build.gradle, test-resources-jdbc/test-resources-jdbc-oracle-xe/build.gradle, test-resources-jdbc/test-resources-jdbc-postgresql/build.gradle, test-resources-kafka/build.gradle, test-resources-mongodb/build.gradle, test-resources-neo4j/build.gradle, test-resources-r2dbc/test-resources-r2dbc-core/build.gradle, test-resources-r2dbc/test-resources-r2dbc-mariadb/build.gradle, test-resources-r2dbc/test-resources-r2dbc-mssql/build.gradle, test-resources-r2dbc/test-resources-r2dbc-mysql/build.gradle, test-resources-r2dbc/test-resources-r2dbc-oracle-xe/build.gradle, test-resources-r2dbc/test-resources-r2dbc-postgresql/build.gradle, test-resources-rabbitmq/build.gradle
Introduce convention plugins to remove some configuration duplication.
All test containers modules now have their own plugin. Similarly,
the JDBC and R2DBC modules share a lot of configuration, so they have
their own plugins now.
=> Refactor build

test-resources-elasticsearch/src/main/java/io/micronaut/testresources/elasticsearch/ElasticsearchTestResourceProvider.java, test-resources-hashicorp-vault/build.gradle, test-resources-hashicorp-vault/src/main/java/io/micronaut/testresources/hashicorp/vault/VaultTestResourceProvider.java, test-resources-hashicorp-vault/src/main/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver, test-resources-hashicorp-vault/src/test/groovy/io/micronaut/testresources/hashicorp/vault/VaultStartedTest.groovy, test-resources-hashicorp-vault/src/test/resources/application-test.yml, test-resources-hashicorp-vault/src/test/resources/bootstrap.yml, test-resources-hivemq/src/main/java/io/micronaut/testresources/hivemq/HiveMQTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-mariadb/src/main/java/io/micronaut/testresources/mariadb/MariaDBTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-mssql/src/main/java/io/micronaut/testresources/mssql/MSSQLTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-mysql/src/main/java/io/micronaut/testresources/mysql/MySQLTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-oracle-xe/src/main/java/io/micronaut/testresources/oracle/xe/OracleXETestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-postgresql/src/main/java/io/micronaut/testresources/postgres/PostgreSQLTestResourceProvider.java, test-resources-kafka/src/main/java/io/micronaut/testresources/kafka/KafkaTestResourceProvider.java, test-resources-mongodb/src/main/java/io/micronaut/testresources/mongodb/MongoDBTestResourceProvider.java, test-resources-neo4j/src/main/java/io/micronaut/testresources/neo4j/Neo4jTestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-core/src/main/java/io/micronaut/testresources/r2dbc/core/AbstractR2DBCTestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-mariadb/src/main/java/io/micronaut/testresources/r2dbc/mariadb/R2DBCMariaDBTestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-mssql/src/main/java/io/micronaut/testresources/r2dbc/mssql/R2DBCMSSQLTestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-mysql/src/main/java/io/micronaut/testresources/r2dbc/mysql/R2DBCMySQLTestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-oracle-xe/src/main/java/io/micronaut/testresources/r2dbc/oracle/R2DBCOracleXETestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-postgresql/src/main/java/io/micronaut/testresources/r2dbc/postgres/R2DBCPostgreSQLTestResourceProvider.java, test-resources-rabbitmq/src/main/java/io/micronaut/testresources/rabbitmq/RabbitMQTestResourceProvider.java, test-resources-redis/src/main/java/io/micronaut/testresources/redis/RedisTestResourceProvider.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/AbstractTestContainersProvider.java, test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/AbstractTestContainersProviderTest.groovy
This commit fixes an inconsistency in the API: for generic test container
providers, the `create` method was only getting the explicit list of
requested properties, but not the test resources configuration map.
This forced implementors which need additional test resources configuration
to explicitly require those properties when they are actually already
available directly.
=> Pass test resources configuration to create method

src/main/docs/guide/modules-testcontainers.adoc, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainers.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainersConfiguration.java, test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/AbstractTestContainersProviderTest.groovy, test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/CustomNetworkTest.groovy, test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy, test-resources-testcontainers/src/test/resources/application-test.yml
This commit adds support for declaring custom networks.
This makes it possible to have containers which directly
communicate with each other.
Fixes #31
=> Add support for custom networks

test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainersConfiguration.java, test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy, test-resources-testcontainers/src/test/resources/some/other-file.txt
This commit introduces the ability to mount classpath files in a container,
or mount classpath directories as volumes in a container.
Fixes #32
=> Implement classpath volume mapping

test-resources-server/src/main/java/io/micronaut/testresources/server/Application.java, test-resources-server/src/main/resources/logback.xml
This commit tweaks the logging of the Micronaut Test Resources server,
to reduce confusion when a build starts: instead of seeing two traditional
Micronaut Application messages, the test resources server will not output
its own message, making it clearer that it's not the user application.
=> Tweak logging for Micronaut Test Resources server

test-resources-kafka/src/main/java/io/micronaut/testresources/kafka/KafkaTestResourceProvider.java
As of v 7.0.4, Confluent are generating ARM versions for their Kafka image 🎉 
https://github.com/confluentinc/kafka-images/blame/5ba80298dcd8d4707555036917ee805b82ed6b87/Jenkinsfile#L20
This change moves from `6.2.1` to `7.0.4` (which seems to be the first one to support it).
On an M1 mac, the startup time is 3s with 7.0.4 and 26s with 6.2.1
=> Update Kafka image to 7.0.4

gradle/libs.versions.toml, settings.gradle, test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java, test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/TestResourcesClasspathTest.groovy, test-resources-r2dbc/test-resources-r2dbc-core/src/main/java/io/micronaut/testresources/r2dbc/core/AbstractR2DBCTestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-core/src/main/java/io/micronaut/testresources/r2dbc/core/R2dbcSupport.java, test-resources-r2dbc/test-resources-r2dbc-pool/build.gradle, test-resources-r2dbc/test-resources-r2dbc-pool/src/main/java/io/micronaut/testresources/r2dbc/pool/R2DBCPoolTestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-pool/src/main/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver, test-resources-r2dbc/test-resources-r2dbc-pool/src/test/groovy/io/micronaut/testresources/r2dbc/pool/ReactiveBookRepository.groovy, test-resources-r2dbc/test-resources-r2dbc-pool/src/test/groovy/io/micronaut/testresources/r2dbc/pool/StandaloneStartPostgreSQLTest.groovy, test-resources-r2dbc/test-resources-r2dbc-pool/src/test/groovy/io/micronaut/testresources/r2dbc/pool/WithJdbcStartPostgreSQLTest.groovy, test-resources-r2dbc/test-resources-r2dbc-pool/src/test/resources/application-jdbc.yml, test-resources-r2dbc/test-resources-r2dbc-pool/src/test/resources/application-standalone.yml, test-resources-r2dbc/test-resources-r2dbc-pool/src/test/resources/logback.xml
This commit introduces an additional resolver for R2DBC, which would configure
the R2DBC pool properties if the `io.r2dbc:r2dbc-pool` dependency is present
on classpath.
Fixes #41
=> Add support for resolving R2DBC pool

src/main/docs/guide/modules-databases-jdbc.adoc, src/main/docs/guide/modules-databases.adoc, test-resources-jdbc/test-resources-jdbc-mssql/src/main/java/io/micronaut/testresources/mssql/MSSQLTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-mssql/src/test/resources/container-license-acceptance.txt, test-resources-r2dbc/test-resources-r2dbc-mssql/build.gradle, test-resources-r2dbc/test-resources-r2dbc-mssql/src/main/java/io/micronaut/testresources/r2dbc/mssql/R2DBCMSSQLTestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-mssql/src/test/resources/application-jdbc.yml, test-resources-r2dbc/test-resources-r2dbc-mssql/src/test/resources/application-standalone.yml, test-resources-r2dbc/test-resources-r2dbc-mssql/src/test/resources/container-license-acceptance.txt
In the starter project, if a user pulls in the TestContainers feature, they get the URL and EULA for `2019-CU4-ubuntu-16.04`
https://github.com/micronaut-projects/micronaut-starter/blob/f7902691bb355c8a4f923dce086b113c846b8346/starter-core/src/main/java/io/micronaut/starter/feature/database/TestContainers.java#L64
https://github.com/micronaut-projects/micronaut-starter/blob/f7902691bb355c8a4f923dce086b113c846b8346/starter-core/src/main/java/io/micronaut/starter/feature/database/TestContainers.java#L148
In the test-resources spike branch of starter, we're seeing weird results if the user now pulls in TestContainers as the feature
writes the EULA for `2019-CU4-ubuntu-16.04` but then the version TestResources starts is `2017-CU2`.
This PR aligns these versions so they are at least the same. …
=> Align MsSQL version with TestContainers in starter

src/main/docs/guide/modules-databases-jdbc.adoc, src/main/docs/guide/modules-databases-r2dbc.adoc, test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-mariadb/src/test/groovy/io/micronaut/testresources/jdbc/mariadb/StartMariaDBWithCustomizationsTest.groovy, test-resources-jdbc/test-resources-jdbc-mariadb/src/test/resources/application-init-script.yml, test-resources-jdbc/test-resources-jdbc-mariadb/src/test/resources/init.sql, test-resources-jdbc/test-resources-jdbc-mariadb/src/test/resources/logback.xml, test-resources-r2dbc/test-resources-r2dbc-mariadb/src/test/groovy/io/micronaut/testresources/r2dbc/mariadb/JdbcWithCustomizationMariaDBSQLTest.groovy, test-resources-r2dbc/test-resources-r2dbc-mariadb/src/test/resources/application-customized-jdbc.yml, test-resources-r2dbc/test-resources-r2dbc-mariadb/src/test/resources/init.sql, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/AbstractTestContainersProvider.java
This commit introduces configuration which will let the user override
the default database name, username and password, as well as running
an init SQL script.
Closes #81
=> Let the user tweak database parameters

test-resources-server/src/main/resources/logback.xml
We don't really need this for the test resources process and it's
causing issues under Windows.
Fixes #76
=> Disable JAnsi output for the test resources service

src/main/docs/guide/quickStart.adoc
I made the mistake of skipping over the Gradle plugin reference when reading about Micronaut Test Resources, so I added a more direct link/more reference to the fact that the Gradle and Maven plugins contain Test Resources-specific information.
=> Hint that Gradle/Maven plugin docs include specific Test Resources docs

test-resources-jdbc/test-resources-jdbc-oracle-xe/src/main/java/io/micronaut/testresources/oracle/xe/OracleXETestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-oracle-xe/src/test/groovy/io/micronaut/testresources/jdbc/xe/OracleATPTest.groovy, test-resources-jdbc/test-resources-jdbc-oracle-xe/src/test/resources/application-prod.yml, test-resources-r2dbc/test-resources-r2dbc-oracle-xe/src/main/java/io/micronaut/testresources/r2dbc/oracle/R2DBCOracleXETestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-oracle-xe/src/test/groovy/io/micronaut/testresources/r2dbc/oracle/OracleATPReactiveTest.groovy, test-resources-r2dbc/test-resources-r2dbc-oracle-xe/src/test/resources/application-prod.yml, test-resources-r2dbc/test-resources-r2dbc-oracle-xe/src/test/resources/application-standaloneprod.yml
In production, when Oracle ATP is used, we wouldn't set the datasource URL, but instead set the `ocid` property (and possibly others). This confuses test resources, because if a property is missing, then it would try to resolve it. Which is what happens here: even if the `url` property is effectively unused when the cloud environment is detected, the property was effectively resolved.
The workaround is to try to see if the `ocid` property is set, in which case the resolvers wouldn't do anything.
=> Avoid spawning an Oracle container when Oracle cloud is used

test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientPropertyExpressionResolver.java, test-resources-client/src/test/groovy/io/micronaut/testresources/client/TestResourcesClientTest.groovy, test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-postgresql/src/main/java/io/micronaut/testresources/postgres/PostgreSQLTestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-core/src/main/java/io/micronaut/testresources/r2dbc/core/AbstractR2DBCTestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-postgresql/src/main/java/io/micronaut/testresources/r2dbc/postgres/R2DBCPostgreSQLTestResourceProvider.java
This commit fixes handling of the resolution result whenever the client throws an error, which is the case if the resolver returns an empty optional. This improves the error message on the client side.
It also improves the PostgreSQL providers so that they support both `postgres` and `postgresql` as `db-type`, since it's a common mistake.
Fixes #129
=> Fix property resolving when client returns a 404

test-resources-client/src/main/java/io/micronaut/testresources/client/ConfigFinder.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientFactory.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientPropertyExpressionResolver.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientPropertySourceLoader.java, test-resources-client/src/test/groovy/io/micronaut/testresources/client/TestResourcesClientPropertiesTest.groovy, test-resources-client/src/test/groovy/io/micronaut/testresources/client/TestServer.groovy
This commit adds the ability for the client to get the server connection details from system properties. Before, the only possible solution was to have a `test-resources.properties` file on classpath.
Because the client and the configuration had to be injected via classpath, it meant that a change to the server configuration would typically invalidate classpath and cause tasks to be out-of-date in Gradle (see https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/579)
The new option makes it possible to read the server configuration from system properties if the file isn't found on classpath. This preserves backwards compatibility while offering a convenient way to pass in the parameters.
Note that we are not using environment variables, because there would be no option to …
=> Support reading server connection details from system properties

test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientFactory.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientPropertySourceLoader.java, test-resources-core/src/main/java/io/micronaut/testresources/core/LazyTestResourcesPropertySourceLoader.java
This method can be used in tests, whenever for some reason it is required to interact with the test resources server directly. This can be the case, for example, if a test should ensure that the resources are closed after the test, in order to avoid exhausting memory.
=> Provide a method to get the client from an application context

src/main/docs/guide/modules-databases-jdbc.adoc
I have lost a very long time because of this and hope to help others avoid such issues.
I suggest to improve the error message in case the value is not properly configured because the cause of the issue was really not evident from the error message I was getting: 
```
Message: Not Found
Path Taken: DataSource.dataSource(DatasourceConfiguration datasourceConfiguration) --> DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
Caused by: io.micronaut.http.client.exceptions.HttpClientResponseException: Not Found
```
=> Fix possible values for db-type in documentation

test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java, test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
This commit fixes an issue with the logic when the AppCDS classpath changes: we have logic to "snapshot" the classpath in order to detect changes. We also have logic to make sure that we build a "flat jar" which contains the contents of all directories on classpath (because AppCDS only supports jars on classpath).
When a directory on classpath changed, for example if we made a change to `src/testResources/main/some/Resource.java`, then we would properly detect the change, but we accidentally deleted the newly generated flat jar.
Fixes #148
=> Fix flat jar being deleted when directories change

src/main/docs/guide/modules-databases.adoc, test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/src/main/java/io/micronaut/testresources/hibernate/reactive/oracle/HibernateReactiveOracleXETestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-oracle-xe/src/main/java/io/micronaut/testresources/oracle/xe/OracleXETestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-oracle-xe/src/main/java/io/micronaut/testresources/r2dbc/oracle/R2DBCOracleXETestResourceProvider.java
This commit updates the default Oracle XE image used to slim-faststart, in order to make it faster to start tests.
Fixes #144
=> Default to Oracle XE slim-faststart

test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java, test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy, test-resources-server/build.gradle, test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesService.java
This will make it look nicer when calling `jps`, for example, but it's a breaking change.
Fixes #116
=> Rename `Application` -> `TestResourcesService`

buildSrc/src/main/groovy/io.micronaut.build.internal.hibernate-reactive-module.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.jdbc-module.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.r2dbc-module.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.testcontainers-module.gradle, gradle/wrapper/gradle-wrapper.properties, settings.gradle, test-resources-build-tools/build.gradle, test-resources-client/build.gradle, test-resources-embedded/build.gradle, test-resources-hashicorp-vault/build.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/build.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/build.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/build.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/build.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/build.gradle, test-resources-jdbc/test-resources-jdbc-core/build.gradle, test-resources-localstack/test-resources-localstack-core/build.gradle, test-resources-localstack/test-resources-localstack-dynamodb/build.gradle, test-resources-localstack/test-resources-localstack-s3/build.gradle, test-resources-r2dbc/test-resources-r2dbc-mariadb/build.gradle, test-resources-r2dbc/test-resources-r2dbc-mssql/build.gradle, test-resources-r2dbc/test-resources-r2dbc-mysql/build.gradle, test-resources-r2dbc/test-resources-r2dbc-oracle-xe/build.gradle, test-resources-r2dbc/test-resources-r2dbc-pool/build.gradle, test-resources-r2dbc/test-resources-r2dbc-postgresql/build.gradle, test-resources-redis/build.gradle, test-resources-server/build.gradle, test-resources-testcontainers/build.gradle
This commit moves to build plugins 6.3.3 and enables standardized project names.
=> Upgrade to build plugins 6.3.3

buildSrc/src/main/groovy/io.micronaut.build.internal.database-testing.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.hibernate-reactive-module.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.jdbc-module.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.kafka-testing.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.localstack-module.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.r2dbc-module.gradle, buildSrc/src/main/groovy/io.micronaut.build.internal.testcontainers-module.gradle, buildSrc/src/main/groovy/io/micronaut/internal/ParallelGateService.java, gradle.properties, test-resources-kafka/build.gradle, test-resources-localstack/test-resources-localstack-core/build.gradle, test-resources-localstack/test-resources-localstack-dynamodb/build.gradle, test-resources-localstack/test-resources-localstack-s3/build.gradle, test-resources-r2dbc/test-resources-r2dbc-pool/build.gradle, test-resources-server/build.gradle
This commit enables parallel building of projects. While I was investigating support for Gradle's configuration cache, I noticed that if the cache is enabled, then projects are built in parallel _even if parallel is false_ or that `--no-parallel` is used. While this may be a bug in Gradle, there is value in supporting parallel builds.
The reason it wasn't done before is that test resources tests are resource intensive: most of them require docker containers. In addition, the tests make assertions on the number of containers which are started. If 2 projects use the same container kind in parallel (say, Kafka), then the assertions would fail, as seen in https://ge.micronaut.io/s/sl32a7lohhmio/tests/:micronaut-test-resources-localstack-s3:test/io.micronaut.testresources.localstack.s3.LocalSta …
=> Enable parallel build

test-resources-elasticsearch/src/main/java/io/micronaut/testresources/elasticsearch/ElasticsearchTestResourceProvider.java, test-resources-embedded/build.gradle, test-resources-embedded/src/main/java/io/micronaut/testresources/embedded/EmbeddedTestResourcesPropertySourceLoader.java, test-resources-embedded/src/test2/groovy/io/micronaut/testresources/embedded/FailingBean.groovy, test-resources-embedded/src/test2/groovy/io/micronaut/testresources/embedded/InvalidTestResourcesTest.groovy, test-resources-embedded/src/test2/groovy/io/micronaut/testresources/embedded/support/FailingResolver.java, test-resources-embedded/src/test2/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver, test-resources-embedded/src/test2/resources/logback.xml, test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java
This commit fixes the test resource resolvers which were returning properties using camel case. In order to make sure new resolvers, or resolvers implemented by users, only make use of kebab case, we added a check in the embedded resolver: this resolver is the one which is used to collect all resolvers from classpath, and is used in both the test resources service and in embedded mode.
Fixes #183
=> Only use kebab case for resolvable properties

test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientFactory.java
Some of them are used in Micronaut Data for particular testing needs.
=> Make all test resources client factory methods public

test-resources-client/src/main/java/io/micronaut/testresources/client/DefaultTestResourcesClient.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClient.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientPropertyExpressionResolver.java, test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java, test-resources-server/src/test/groovy/io/micronaut/testresources/server/TestResourcesControllerTest.groovy, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainers.java
This causes errors with the HTTP client. As it is an API breaking change, it's only for 2.0.0.
=> Fix close methods returning void

buildSrc/src/main/groovy/io.micronaut.build.internal.test-fixtures.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-core/build.gradle, test-resources-jdbc/test-resources-jdbc-core/build.gradle, test-resources-localstack/test-resources-localstack-core/build.gradle, test-resources-testcontainers/build.gradle
Those test fixtures were published on Maven Central, but they are not intended for external consumption. This will make the publication of Micronaut Test Resources 2.0.0 easier, since we won't depend on any other Micronaut module (except for core).
=> Remove publication of test fixtures

src/main/docs/guide/modules-testcontainers.adoc, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java, test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy
`testcontainers-java` added [tmpfs](https://docs.docker.com/storage/tmpfs/) support in https://github.com/testcontainers/testcontainers-java/issues/673. This allows for containers to have lightning fast ephemeral storage, which may be preferable for containers that are for data storage. (e.g. elasticsearch container is _way_ faster with a tmpfs bind).
This PR adds the option to configure tmpfs mappings on `GenericContainer`s.
Follow up PRs could add true/false tmpfs mapping option to jdbc/mongo/elasticsearch.
=> Add tmpfs support

src/main/docs/guide/modules-mongodb.adoc, test-resources-mongodb/src/main/java/io/micronaut/testresources/mongodb/MongoDBTestResourceProvider.java, test-resources-mongodb/src/test/groovy/io/micronaut/testresources/mongodb/BookRepository.groovy, test-resources-mongodb/src/test/groovy/io/micronaut/testresources/mongodb/MultipleMongoDBTest.groovy, test-resources-mongodb/src/test/groovy/io/micronaut/testresources/mongodb/User.groovy, test-resources-mongodb/src/test/groovy/io/micronaut/testresources/mongodb/UserRepository.groovy, test-resources-mongodb/src/test/resources/application-multiple-servers.yml
This commit adds the ability to use multiple MongoDB databases. It's worth noting that we will spawn a _single_ MongoDB container, and that the name of the replica set is going to be set to the database name in your Micronaut configuration.
Closes #142
=> Add support for multiple mongodb server uris

test-resources-jdbc/test-resources-jdbc-mssql/src/main/java/io/micronaut/testresources/mssql/MSSQLTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-mssql/src/test/groovy/io/micronaut/testresources/mssql/MSSQLTestResourceProviderSpec.groovy
solve issues found in starter
```
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
at io.micronaut.testresources.mssql.MSSQLTestResourceProvider.createMSSQLContainer(MSSQLTestResourceProvider.java:50)
``
=> fix: handle accept license as string

src/main/docs/guide/extensions-core.adoc, src/main/docs/guide/extensions-junit-platform.adoc, src/main/docs/guide/extensions.adoc, src/main/docs/guide/toc.yml
This commit adds user documentation for the new Micronaut Test extensions available in test resources.
This is a follow up to #231 and #241
=> Documentation for Micronaut test extensions

test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java
or the other way around. Currently, if both the MariaDB and MySQL test resources providers are present, then because they share the same dialect, it is possible that we select one provider or the other randomly, based on which comes first.
To fix this, we now make sure that if the `db-type` property is set, then we only return a container if it is actually capable of handling that db type. Since this test comes first, before the dialect, it has higher precedence and we wouldn't pick one container for the other.
=> Make sure we can't use MariaDB instead of MySQL

test-resources-extensions/test-resources-extensions-junit-platform/build.gradle, test-resources-extensions/test-resources-extensions-junit-platform/src/koTest/kotlin/io/micronaut/test/extensions/junit5/BeforeSpecScopeTest.kt, test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/ScopeHolder.java, test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/SpockScopeExtension.java, test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/TestResourcesLauncherSessionListener.java, test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/TestResourcesScopeListener.java, test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/annotation/ScopeNamingStrategy.java, test-resources-extensions/test-resources-extensions-junit-platform/src/main/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener, test-resources-extensions/test-resources-extensions-junit-platform/src/main/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener, test-resources-extensions/test-resources-extensions-junit-platform/src/main/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension, test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/SetupAnnotationScopeTest.groovy, test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/SharedAnnotationScopeTest.groovy
This commit fixes a few issues with the current scope listening implementation:
1. use the test class for naming strategy instead of the test id: this avoids leaking the launcher API types and makes it easier to use without JUnit specific APIs
2. whenever tests were using a single JVM but multiple sessions, which happens when test distribution is enabled, then the scopes could be closed even if the next session had a test reusing the same scope
3. Spock provides a `@Shared` annotation which can be used to initialize shared state, but this code is executed _before_ the test is considered started, which breaks the assumption made in the scope listener
This should fix issues with Micronaut Data not closing scopes.
=> Fix scope listeners

config/accepted-api-changes.json, test-resources-client/build.gradle, test-resources-client/src/main/java/io/micronaut/testresources/client/DefaultTestResourcesClient.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientFactory.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientPropertyExpressionResolver.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesException.java, test-resources-client/src/test/groovy/io/micronaut/testresources/client/TestServer.groovy, test-resources-server/build.gradle
There are 2 reasons to make that change:
1. reduce the number of dependencies of the client, in order to remove the dependency on Netty
2. the JDK HTTP client doesn't need to be closed
The 2d point deserves a bit more information. The test resources client factory is called by the test resources client, and in general, there should be at most a couple calls per build. In practice, this isn't the case: in Micronaut Data for example, there are many calls because tests spawn their own application context.
One issue is that Micronaut Core will _not_ call `#close` on a `PropertySourceLoader` once an application context is closed, even if that loader implements `Closeable`. It is arguable if it's a bug or not, but in practice, it means that there is no way for Micronaut Test Resources to …
=> Switch to using the Java HTTP client

test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java, test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/TestResourcesClasspathTest.groovy
This will be needed for issue https://github.com/micronaut-projects/micronaut-r2dbc/issues/357
After this is merged, will have to update micronaut test resources gradle plugin with test resources version and then subsequently update micronaut-r2dbc and micronaut-data.
There are currently issues in micronaut-r2dbc and micronaut-data due to serialization or http issues so won't be merging this until issues are resolved.
=> Update r2dbc mysql driver

test-resources-server/build.gradle, test-resources-server/src/aot/aot.properties
The previous fix (#266) wasn't sufficient, as when you don't use any YAML configuration file, the YAML property source loader is still added my Micronaut AOT to the list of services which are "statically" loaded. This probably requires a fix in Micronaut AOT. In between, this configuration makes sure that the loader isn't added.
=> Fix YamlPropertySourceLoader being added on classpath

src/main/docs/guide/quickStart.adoc
The parentheses surrounding the links are breaking the links. With the original form: 
(www.whatever.com)Whatever
The output looks something like this: 
(Whatever 
and then the link goes to: www.whatever.com)
=> Removed parentheses to fix links

test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientFactory.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientPropertyExpressionResolver.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientPropertySourceLoader.java, test-resources-client/src/test/groovy/io/micronaut/testresources/client/TestResourcesClientPropertiesTest.groovy, test-resources-client/src/test/groovy/io/micronaut/testresources/client/TestResourcesClientTest.groovy
In normal operation mode, the server settings are passed to the client via system properties. This lets the client figure out on which server to connect. In particular, there may be more than one test resources server running, and there can be shared servers as well as namespaced servers.
However, in practice IDEs may not delegate to the build tool, which means that the configuration is not passed to the client. We want to make it possible to support the following scenario:
1. start a test resources service from command line via the build tool, e.g `mvn mn:start-test-resources-service`
2. in the IDE, run tests or main application without delegating to the build tool
3. tests should pass
It is currently working by accident for tests in Maven, because the properties file is on classpath. It …
=> Let the client factory find local configuration files

gradle/libs.versions.toml, test-resources-elasticsearch/build.gradle, test-resources-hashicorp-vault/build.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-core/build.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/build.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/build.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/build.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/build.gradle, test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/build.gradle, test-resources-hivemq/build.gradle, test-resources-jdbc/test-resources-jdbc-core/build.gradle, test-resources-jdbc/test-resources-jdbc-mariadb/build.gradle, test-resources-jdbc/test-resources-jdbc-mssql/build.gradle, test-resources-jdbc/test-resources-jdbc-mysql/build.gradle, test-resources-jdbc/test-resources-jdbc-oracle-xe/build.gradle, test-resources-jdbc/test-resources-jdbc-postgresql/build.gradle, test-resources-kafka/build.gradle, test-resources-localstack/test-resources-localstack-core/build.gradle, test-resources-mongodb/build.gradle, test-resources-neo4j/build.gradle, test-resources-r2dbc/test-resources-r2dbc-core/build.gradle, test-resources-r2dbc/test-resources-r2dbc-mariadb/build.gradle, test-resources-r2dbc/test-resources-r2dbc-mssql/build.gradle, test-resources-r2dbc/test-resources-r2dbc-mysql/build.gradle, test-resources-r2dbc/test-resources-r2dbc-oracle-xe/build.gradle, test-resources-r2dbc/test-resources-r2dbc-postgresql/build.gradle, test-resources-rabbitmq/build.gradle, test-resources-redis/build.gradle, test-resources-testcontainers/build.gradle
Currently only the version is managed, so the individual modules are not visible when using catalogs.
=> Make testcontainers dependencies managed

test-resources-hashicorp-vault/src/main/java/io/micronaut/testresources/hashicorp/vault/VaultTestResourceProvider.java
The `latest` tag is no longer available.
=> Use a fixed version for Vault

src/main/docs/guide/modules-testcontainers.adoc, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/GenericTestContainerProvider.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainersConfiguration.java, test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/ContainerDependenciesTest.groovy, test-resources-testcontainers/src/test/resources/application-test.yml
Because of technical reasons, the support is currently limited to generic containers: in this case, we know that the `properties` map which is passed when resolving a property will always be empty, because a generic container cannot declare such required properties. Therefore, when a container is resolved, we can look into the _other_ generic containers which are declared, and see if one matches the required id. If we find one, then we can trigger the resolution of the container by resolving one of the properties it provides (any property works).
This feature does _not_ rely on the `dependsOn` feature of Testcontainers for the very same reason: the resolver doesn't have access to other containers which are resolved, nor does it know how to create one at the point in time the resolution is …
=> Add support for dependencies between containers

gradle.properties, test-resources-core/src/main/java/io/micronaut/testresources/core/ToggableTestResourcesResolver.java, test-resources-embedded/src/main/java/io/micronaut/testresources/embedded/EmbeddedTestResourcesPropertyExpressionResolver.java, test-resources-embedded/src/main/java/io/micronaut/testresources/embedded/EmbeddedTestResourcesPropertySourceLoader.java, test-resources-r2dbc/test-resources-r2dbc-pool/src/main/java/io/micronaut/testresources/r2dbc/pool/R2DBCPoolTestResourceProvider.java, test-resources-r2dbc/test-resources-r2dbc-pool/src/test/groovy/io/micronaut/testresources/r2dbc/pool/R2DBCPoolDisablingTest.groovy, test-resources-r2dbc/test-resources-r2dbc-pool/src/test/resources/application-r2dbc-pool-disabled.yml, test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/AbstractTestContainersProvider.java, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/GenericTestContainerProvider.java
This commit introduces a property to disable a test resolver. It was implemented in a backwards compatible fashion, by introducing a new subtype of resolver. Resolvers which can be disabled need to implement the `ToggableTestResourcesResolver` interface and provide a name.
This name is used at resolution time, to figure out a test resources property. For example, if the name of the resolver is foo, then at resolution time, we'd look into the test resources configuration for the property:
test-resources.foo.enabled
and ignore the resolver if that property is `false`. This flag should only be used for debugging purposes.
Fixes #399
=> Add property to disable some test resources resolvers

test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java, test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/TestResourcesClasspathTest.groovy
Support added for mysql-connector-j besides already supported mysql-connector-java, needed for [micronaut-sql](https://github.com/micronaut-projects/micronaut-sql/pull/1106) and [starter](https://github.com/micronaut-projects/micronaut-starter/pull/2064)
=> Add support for mysql-connector-j

gradle/libs.versions.toml, settings.gradle, test-resources-hashicorp-vault/src/main/java/io/micronaut/testresources/hashicorp/vault/VaultTestResourceProvider.java
**Update versions for:**
micronaut => "3.10.1"
micronaut-test => "3.9.2"
micronaut-gradle-plugin => "3.7.10"
groovy => "3.0.19"
spock => "2.4-M1-groovy-3.0"
vertx-client => "4.4.5"
The update of the testcontainers-dependency also brought in the change of the hashicorpt-vault image name.
It changed from **vault** to **hashicorp/vault**, which is fixed in this PR.
=> Updated versions

.editorconfig, .github/workflows/graalvm-latest.yml, .github/workflows/gradle.yml, settings.gradle, test-resources-server/src/test/groovy/io/micronaut/testresources/server/TestResourcesControllerTest.groovy, test-resources-server/src/test/resources/logback.xml, test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainers.java
Supersedes #415 to stop micronaut-build force pushing it all the time
=> Fix java 21 build

test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientFactory.java
When reading the configuration from convention, it can be useful to pass the namespace via an env var.
=> Allow getting the test resources namespace from an environment variable

gradle.properties, test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerSettings.java, test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java, test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClient.java, test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesKeepAlive.java, test-resources-server/src/main/java/io/micronaut/testresources/server/ExpiryManager.java, test-resources-server/src/main/java/io/micronaut/testresources/server/Ping.java, test-resources-server/src/main/java/io/micronaut/testresources/server/PropertyResolutionListener.java, test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java, test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesService.java
This commit introduces a server idle timeout. By default, after one hour without receiving requests, the server will shut down. Configuring the idle timeout will require updates to the build plugin integrations.
The client will send one request per minute to the server in order to keep it alive.
Fixes #443
=> Add a server idle timeout

test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/ControlPanelPropertyResolutionListener.java, test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/TestResourcesControlPanel.java, test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/TestResourcesControlPanelBody.java, test-resources-control-panel/src/main/resources/views/test-resources/body.hbs, test-resources-control-panel/src/main/resources/views/test-resources/detail.hbs, test-resources-core/src/main/java/io/micronaut/testresources/core/TestResourcesResolutionException.java, test-resources-server/src/main/java/io/micronaut/testresources/server/PropertyResolutionListener.java, test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java
With this change, the control panel will now remember resolution errors. This can be particularly useful when resolution fails on the client side, and that the user doesn't really understand why.
By going to the control panel, the errors will be recorded per resolver.
Here's a screenshot of the control panel main page for a resolver with an error:
Then on the details page:
=> Record resolution errors for control panel

test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java, test-resources-server/src/main/resources/application.properties
It seems that in some cases, even if the default stop endpoint is called, the server is not shutdown properly. This seems to happen if some containers are started, but not in all cases. With this change, we switch from using the `/stop` endpoint from management to a custom one which times out after 5s, making sure the server is killed.
=> Fix server not shutting down

test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java, test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
This commit fixes a bug where we would not wait for the test resources service to be available when using an explicit port. Instead, the utility was returning immediately, which caused the test resources client to fail if it tried to connect before the service had a chance to initialize. This problem can surface more easily when, during startup, we perform tests like checking that Docker is available.
=> Fix server startup utils

gradle/libs.versions.toml
This should fix the problem with the mysql:latest image not being compatible, as seen in several places like
https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/927 or https://github.com/micronaut-projects/micronaut-test/pull/936 or https://github.com/micronaut-projects/micronaut-test-resources/pull/503/files
=> Upgrade testcontainers dependency

test-resources-extensions/test-resources-extensions-junit-platform/gradle.properties
This is because we use Kotlin in tests, but not in production code.
=> Remove accidental dependency on kotlin stdlib

gradle.properties, settings.gradle, src/main/docs/guide/modules-databases-jdbc.adoc, src/main/docs/guide/modules-databases.adoc, test-resources-elasticsearch/src/main/java/io/micronaut/testresources/elasticsearch/ElasticsearchTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-mysql/build.gradle, test-resources-jdbc/test-resources-jdbc-mysql/src/main/java/io/micronaut/testresources/mysql/MySQLTestResourceProvider.java, test-resources-jdbc/test-resources-jdbc-mysql/src/test/groovy/io/micronaut/testresources/jdbc/mysql/StartMySQLTest.groovy
This PR:
- Uses [the real official MySQL image](https://blogs.oracle.com/mysql/post/where-to-find-official-mysql-container-images).
- Resolves a new property to allow using [MySQL Document Store](https://dev.mysql.com/doc/connector-j/en/connector-j-using-xdevapi.html).
=> Enhancements to the MySQL support

test-resources-extensions/test-resources-extensions-core/src/main/java/io/micronaut/test/extensions/testresources/TestResourcesPropertiesFactory.java, test-resources-extensions/test-resources-extensions-core/src/test/java/io/micronaut/test/extensions/testresources/MetaAnnotationTestResourcesPropertiesTest.java
See #571 
* If direct annotation on test class is not found, then look for meta annotations.
* Fixes typo on `instantiateProvider`.
=> feat(#571): TestResourcesPropertiesFactory supports user defined meta annotations
